'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleAnalytics } from '@next/third-parties/google'
// import NavBar from '../components/navbar/page';
// import Footer from '../components/footer/page';
import React, { Suspense, useEffect, useState } from 'react'
// import SideBar from '../components/sidebar/page';

const inter = Inter({ subsets: [ 'latin' ] })

// export const metadata = {
//   title: 'Eternal games',
//   description: 'Generated by create next app'
// }

export default function RootLayout({ children }) {
  const [ openSideBar, setOpenSideBar ] = useState(false)

  function handleToggle() {
    setOpenSideBar((prevState) => !prevState)
  }

  return (
      <html lang="en">
      <body className={`w-screen text-white min-h-screen overflow-x-hidden ${inter.className}`}>
      {/*<Suspense>*/}
      {/*  <NavBar toggleSideBar={handleToggle} />*/}
      {/*</Suspense>*/}
      <Suspense>
        {children}
      </Suspense>

      {/*<div className={`w-full ${openSideBar ? 'h-screen overflow-y-scroll ' : ''}`}>*/}
      {/*    <SideBar isOpen={openSideBar} onClose={handleToggle} />*/}
      {/*  <div className={` ${openSideBar ? 'xs:ml-auto base:ml-[190px] h-screen overflow-y-scroll' : ''}`}>*/}

      {/*  </div>*/}
      {/*</div>*/}
      {/*<Suspense>*/}
      {/*  <Footer />*/}
      {/*</Suspense>*/}
      </body>
      <GoogleAnalytics gaId="G-TF62GHPFEJ"/>
      </html>
  )
}
