'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '../components/navbar/page'
import Footer from '../components/footer/page'
import React, { Suspense, useEffect, useState } from 'react';
import SideBar from '../components/sidebar/page';

const inter = Inter({ subsets: [ 'latin' ] })

// export const metadata = {
//   title: 'ZenGames',
//   description: 'Generated by create next app'
// }

export default function RootLayout({ children }) {

  const [ openSideBar, setOpenSideBar ] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth > 600 && openSideBar) {
        setOpenSideBar(false)
      }
    }

    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  })

  function handleToggle() {
    setOpenSideBar((prevState) => !prevState)
  }

  return (
      <html lang="en">
      <body className={`min-h-screen ${inter.className}`}>
      <Suspense>
        <NavBar toggleSideBar={handleToggle}/>
      </Suspense>
      <div>
        <SideBar isOpen={openSideBar} onClose={handleToggle}/>

        {children}
      </div>
      <Suspense>
        <Footer/>
      </Suspense>
      </body>
      </html>
  )
}
