import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/app/components/navbar/page'
import { Suspense } from 'react'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata = {
  title: 'ZenGames',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Suspense>
        <NavBar/>
      </Suspense>
      {children}
      </body>
      </html>
  )
}
